###
GET http://localhost:3000

###
GET http://localhost:3000/categories

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "userName": "lill H",
    "email": "adbc@example.com",
    "password": "testpassword123"
}

###
GET http://localhost:3000/posts

### specific post
GET http://localhost:3000/posts/12

### athletes in category
GET http://localhost:3000/categories/Snow

### athlete profile details
GET http://localhost:3000/circles/2

### circle fans
GET http://localhost:3000/circles/25/fans

### circle post
GET http://localhost:3000/posts/all/3

### list of user circles 
GET http://localhost:3000/user-circles/17129ae3-ba35-4b3f-bdc2-5083c09d868d

### feed for the user
GET http://localhost:3000/user-circles/feed/ab71881f-dc4f-4481-a689-55e506679a5e


### joining a circle
POST http://localhost:3000/user-circles/
Content-Type: application/json

{
    "userId": "17129ae3-ba35-4b3f-bdc2-5083c09d868d",
    "circleId": "12",
    "circleTier": "Bronze",
    "paymentMethod": "Card"
}

### leaving a circle
DELETE http://localhost:3000/user-circles/8

### show all users
GET http://localhost:3000/users/

### show user
GET http://localhost:3000/users/e92d107d-69d9-4ec1-9d1a-90daa9a5c41a

### edit user
PATCH http://localhost:3000/users/e92d107d-69d9-4ec1-9d1a-90daa9a5c41a
Content-Type: application/json

{
    "userEmail": "cococo@example.com"
}

### 
PATCH http://localhost:3000/users/e92d107d-69d9-4ec1-9d1a-90daa9a5c41a
Content-Type: application/json

{
    "userAvatar": "/images/users/cute-alpaca.png"
}

### deleting a profile
DELETE http://localhost:3000/users/a59b9292-8cf4-4dc2-b550-9ee89e9a3d2b

